// List of all available peptide JSON files
// This file can be automatically generated or manually maintained
export const PEPTIDE_FILES = [
  'LLLPPQPALA.json',
  'AAFAGRATA.json',
  'AAAFAGRAT.json',
  'MLPGLALLL.json',
  'ALLPLLLQA.json',
  'AARALLPLL.json',
  'VLWTRIAST.json',
  'LLALLLPQV.json',
  'MLLSLDFPG.json',
  'CLVVAMLLSL.json',
  'MLLSLDFPGQA.json',
  'GALLLWQLL.json',
  'LLLGRLTGV.json',
  'LLLGRLTGVAG.json',
  'WLLAVPGAN.json',
  'FLDETLRSLA.json',
  'EPLLLGRGLIVY.json',
  'RIARALALVVT.json',
  'LLAARVVAA.json',
  'ALFLGVGVR.json',
  'ALGGHPLLGV.json',
  'ALLGALLAA.json',
  'ALLGALLAAA.json',
  'TMDTLRSRT.json',
  'TPHVNHHMP.json',
  'GPARSHLRA.json',
  'GLGPLLGRA.json',
  'LRAASWRSGL.json',
  'LQRHQSQAEP.json',
  'LPPRALALL.json',
  'RRPPRALALL.json',
  'LVSWPRPLLLLV.json',
  'LHEEHSRAAA.json',
  'LLHEEHSRAAA.json',
  'IVLEGPAPA.json',
  'TRLLPALFLVL.json',
  'SPVLILFSS.json',
  'AVPSTGASK.json',
  'GTAVPSTGASK.json',
  'FLIFLLNFT.json',
  'IFLIFLLNF.json',
  'KWVESIFLI.json',
  'IFLIFLLNFT.json',
  'KWVESIFLIF.json',
  'MKWVESIFLI.json',
  'KWVESIFLIFL.json',
  'MKWVESIFLIF.json',
  'IFLYQVVHF.json',
  'LLFRGCLIGA.json',
  'LLLGSPAAA.json',
  'VLLSQLPTV.json',
  'ALLSRPALTLL.json',
  'LLFDWSGTGRA.json',
  'LLTGLVLIL.json',
  'LQRSSGAAA.json',
  'MSLLLLLLLVSY.json',
  // Note: This is a subset for improved maintainability
  // Full list moved to external configuration
] as const;

export type PeptideFileName = typeof PEPTIDE_FILES[number];