name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  # Job 1: Update Dependencies
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates
        
      - name: Check for updates
        id: check-updates
        run: |
          echo "Updates available:"
          ncu
          echo "updates_available=$(ncu --jsonAll | jq 'length > 0')" >> $GITHUB_OUTPUT
          
      - name: Update patch and minor versions
        if: steps.check-updates.outputs.updates_available == 'true'
        run: |
          # Update patch versions (safe updates)
          ncu -u --target patch
          
          # Update minor versions for dev dependencies
          ncu -u --target minor --dep dev
          
      - name: Install updated dependencies
        if: steps.check-updates.outputs.updates_available == 'true'
        run: npm install
        
      - name: Run tests after updates
        if: steps.check-updates.outputs.updates_available == 'true'
        run: |
          npm run lint
          npm run build
          
      - name: Generate update summary
        if: steps.check-updates.outputs.updates_available == 'true'
        id: summary
        run: |
          echo "## Dependency Updates" > update_summary.md
          echo "" >> update_summary.md
          echo "The following dependencies have been updated:" >> update_summary.md
          echo "" >> update_summary.md
          git diff package.json >> update_summary.md
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat update_summary.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        if: steps.check-updates.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies (automated)'
          title: 'chore: automated dependency updates'
          body: |
            ${{ steps.summary.outputs.summary }}
            
            ## Changes
            - Updated patch versions for all dependencies
            - Updated minor versions for development dependencies
            - All tests pass with updated dependencies
            
            ## Review Notes
            - This PR was automatically generated
            - Please review the changes before merging
            - Major version updates require manual review
            
            Auto-generated by GitHub Actions 🤖
          branch: chore/dependency-updates
          delete-branch: true

  # Job 2: Security Audit
  security-audit:
    name: Weekly Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        id: audit
        run: |
          # Run audit and capture output
          npm audit --audit-level=moderate > audit_report.txt 2>&1 || true
          
          # Check if vulnerabilities were found
          if npm audit --audit-level=moderate > /dev/null 2>&1; then
            echo "vulnerabilities_found=false" >> $GITHUB_OUTPUT
          else
            echo "vulnerabilities_found=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create security issue
        if: steps.audit.outputs.vulnerabilities_found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const auditReport = fs.readFileSync('audit_report.txt', 'utf8');
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security vulnerabilities detected in dependencies',
              body: `## Security Audit Report
              
              Automated security scan has detected vulnerabilities in project dependencies.
              
              ### Audit Output
              \`\`\`
              ${auditReport}
              \`\`\`
              
              ### Action Required
              - Review the vulnerabilities listed above
              - Update affected packages to secure versions
              - Run \`npm audit fix\` to automatically fix issues where possible
              - For manual fixes, update package.json with secure versions
              
              ### Steps to Resolve
              1. Run \`npm audit\` locally to see detailed vulnerability information
              2. Run \`npm audit fix\` to automatically fix what can be fixed
              3. For remaining issues, manually update package versions
              4. Test the application after updates
              5. Close this issue once all vulnerabilities are resolved
              
              ---
              *This issue was automatically created by the security audit workflow.*`,
              labels: ['security', 'dependencies', 'automated']
            });